### ISSUE TITLE
SD_WebUI_V1.6.0 does not support python3.8

### ISSUE THREAD

**Issue by SLi-Man** [xuhuisheng/rocm-gfx803#34]
When I use the Pytorch built by this repositorie, it means that I need to use Python3.8 to run Stable Diffusion. After testing, Python3.8 will report an error in the official Stable Diffusion V1.6.0, indicating that the Stable Diffusion V1.6.0 will appear. Do not support python3.8, which version of Stable Diffusion should be used in python3.8 can make it run.

> Python 3.8.10 (default, Jun  4 2021, 15:09:15) 
> [GCC 7.5.0]
> Version: v1.6.0
> Commit hash: 5ef669de080814067961f28357256e8fe27544f4
> Installing clip
> Installing requirements for CodeFormer
> Installing requirements
> Launching Web UI with arguments: --listen --enable-insecure-extension-access --opt-sdp-attention --skip-torch-cuda-test
> /home/sliman/miniconda3/envs/py38/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/sliman/miniconda3/envs/py38/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
>   warn(f"Failed to load image Python extension: {e}")
> no module 'xformers'. Processing without...
> no module 'xformers'. Processing without...
> Traceback (most recent call last):
>   File "launch.py", line 48, in <module>
>     main()
>   File "launch.py", line 44, in main
>     start()
>   File "/home/sliman/stable-diffusion-webui/modules/launch_utils.py", line 432, in start
>     import webui
>   File "/home/sliman/stable-diffusion-webui/webui.py", line 13, in <module>
>     initialize.imports()
>   File "/home/sliman/stable-diffusion-webui/modules/initialize.py", line 33, in imports
>     from modules import shared_init
>   File "/home/sliman/stable-diffusion-webui/modules/shared_init.py", line 5, in <module>
>     from modules import shared
>   File "/home/sliman/stable-diffusion-webui/modules/shared.py", line 5, in <module>
>     from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
>   File "/home/sliman/stable-diffusion-webui/modules/options.py", line 74, in <module>
>     class Options:
>   File "/home/sliman/stable-diffusion-webui/modules/options.py", line 77, in Options
>     def __init__(self, data_labels: dict[str, OptionInfo], restricted_opts):
> TypeError: 'type' object is not subscriptable

My environment
Ubuntu 22.04.3 LTS x86_64
RX580 8G(gfx803)
Python3.8.10

**Comment by josephnglynn** [comment]
v1.5.2 works
